import {fileURLToPath} from 'node:url';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import http from 'node:http';
import {spawn,spawnSync} from 'node:child_process';
import {renderBrief} from '../scripts/lib/site-brief.mjs';
const root=fileURLToPath(new URL('..',import.meta.url));
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jWZkAAAAASUVORK5CYII=','base64');
function fixture(){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'wd-editor-test-'))),site=path.join(dir,'site');const brief={schemaVersion:1,name:'A supplied studio',navigation:[{label:'Home',href:'index.html'},{label:'About',href:'about/index.html'}],pages:[{path:'index.html',title:'Home',description:'Supplied description.',sections:[{id:'welcome',type:'hero-split',title:'Original headline',body:'Work may take up to 20 days.',image:{src:'asset.png',alt:'Original sample'}}]},{path:'about/index.html',title:'About',description:'About this supplied studio.',sections:[{id:'about',type:'hero-editorial',title:'About the studio',body:'A supplied biography.'}]}]};fs.writeFileSync(path.join(dir,'input.json'),JSON.stringify(brief));const run=spawnSync(process.execPath,[root+'scripts/create-site.mjs',`--target=${site}`,`--brief=${dir}/input.json`],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);fs.writeFileSync(path.join(site,'asset.png'),png);fs.writeFileSync(path.join(site,'notes.txt'),'Keep this file.');return{dir,site};}
async function start(t,site,loader){const probe=net.createServer();await new Promise((resolve,reject)=>probe.once('error',reject).listen(0,'127.0.0.1',resolve));const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));const child=spawn(process.execPath,[...(loader?['--import',loader]:[]),root+'scripts/edit-site.mjs',`--dir=${site}`,`--port=${port}`],{stdio:['ignore','pipe','pipe']});t.after(()=>child.kill());const url=await new Promise((resolve,reject)=>{let out='',err='';const timer=setTimeout(()=>{child.kill();reject(Error('Editor did not start'))},8000);child.stderr.on('data',s=>{err+=s});child.stdout.on('data',s=>{out+=s;const match=out.match(/http:\/\/127\.0\.0\.1:\d+\/__editor__\/#([A-Za-z0-9_-]+)/);if(match){clearTimeout(timer);resolve(match[0]);}});child.once('exit',code=>{clearTimeout(timer);reject(Error(`Editor exited ${code}: ${err}`))});});const u=new URL(url),origin=u.origin,token=u.hash.slice(1);return{child,url,origin,token,api:async(endpoint,payload={},headers={})=>{const response=await fetch(origin+'/__api/'+endpoint,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Site-Editor-Token':token,...headers},body:JSON.stringify(payload)});return{status:response.status,body:await response.json()};}};}
function outputs(site){return Object.fromEntries(['index.html','about/index.html','styles.css','site.json','README.md'].map(f=>[f,fs.readFileSync(path.join(site,f),'utf8')]));}
test('unsupported local image formats are explained before editor writes or saves',async t=>{const{site}=fixture();const brief=JSON.parse(fs.readFileSync(site+'/site.json'));brief.pages[0].sections[0].image.src='logo.svg';for(const[file,body]of Object.entries(renderBrief(brief).files))fs.writeFileSync(path.join(site,file),body);const before=outputs(site);const opened=spawnSync(process.execPath,[root+'scripts/edit-site.mjs','--dir='+site,'--port=4379'],{encoding:'utf8',timeout:1500});assert.equal(opened.status,1);assert.match(opened.stderr,/pages\.0\.sections\.0\.image\.src/);assert.match(opened.stderr,/preserve|keep/i);assert.deepEqual(outputs(site),before);assert.equal(fs.existsSync(site+'/.site-editor-history'),false);const next=fixture(),editor=await start(t,next.site),state=(await editor.api('state')).body;const saved=await editor.api('save',{sourceHash:state.sourceHash,changes:[{path:'pages.0.sections.0.image.src',value:'logo.svg'}]});assert.ok(saved.status>=400);assert.equal(JSON.parse(fs.readFileSync(next.site+'/site.json')).pages[0].sections[0].image.src,'asset.png');});
test('editor saves escaped fields across pages, undo/redo and restart persist',async t=>{const{site}=fixture(),before=outputs(site);const editor=await start(t,site);let result=await editor.api('state');assert.equal(result.status,200);const oldHash=result.body.sourceHash;result=await editor.api('save',{sourceHash:oldHash,changes:[{path:'pages.1.sections.0.title',value:'Changed <script>alert(1)</script>'},{path:'name',value:'New supplied studio'}]});assert.equal(result.status,200,JSON.stringify(result.body));assert.match(fs.readFileSync(site+'/about/index.html','utf8'),/Changed &lt;script&gt;/);assert.match(fs.readFileSync(site+'/index.html','utf8'),/New supplied studio/);assert.equal((await editor.api('save',{sourceHash:oldHash,changes:[{path:'name',value:'Stale'}]})).status,409);result=await editor.api('undo',{sourceHash:result.body.sourceHash});assert.equal(result.status,200);assert.deepEqual(outputs(site),before);result=await editor.api('redo',{sourceHash:result.body.sourceHash});assert.equal(result.status,200);editor.child.kill();await new Promise(r=>editor.child.once('exit',r));const restarted=await start(t,site);assert.equal((await restarted.api('state')).status,200);assert.equal(fs.readFileSync(site+'/notes.txt','utf8'),'Keep this file.');});
test('editor rejects unauthorized, unknown-field, traversal, script and stale external edits',async t=>{const{site}=fixture(),editor=await start(t,site),before=outputs(site),state=(await editor.api('state')).body;assert.equal((await editor.api('state',{}, {Origin:'https://outside.example'})).status,403);assert.equal((await editor.api('state',{}, {'X-Site-Editor-Token':'wrong'})).status,403);const wrongHost=await new Promise((resolve,reject)=>{const req=http.request(editor.origin+'/__api/state',{method:'POST',headers:{Host:'outside.example'}},res=>{res.resume();resolve(res.statusCode)});req.on('error',reject);req.end('{}');});assert.equal(wrongHost,421);for(const change of [{path:'__proto__.polluted',value:'yes'},{path:'pages.0.path',value:'outside/index.html'},{path:'pages.0.sections.0.image.src',value:'javascript:alert(1)'},{path:'name',value:'x'.repeat(300)}]){const r=await editor.api('save',{sourceHash:state.sourceHash,changes:[change]});assert.ok(r.status>=400);assert.deepEqual(outputs(site),before);}for(const f of ['site.json','notes.txt','.site-editor-history/original-site.json'])assert.ok((await fetch(editor.origin+'/__preview__/'+f)).status>=400);const page=await fetch(editor.origin+'/__preview__/index.html');assert.match(page.headers.get('content-security-policy'),/script-src 'none'/);fs.appendFileSync(site+'/about/index.html','<!-- manual edit -->');assert.equal((await editor.api('save',{sourceHash:state.sourceHash,changes:[{path:'name',value:'Unsafe overwrite'}]})).status,409);assert.match(fs.readFileSync(site+'/about/index.html','utf8'),/manual edit/);});
test('editor rejects unsafe image bodies and preview symlink escapes',async t=>{const{site,dir}=fixture(),editor=await start(t,site);const headers={Origin:editor.origin,'X-Site-Editor-Token':editor.token,'Content-Type':'image/png'};let response=await fetch(editor.origin+'/__api/image',{method:'POST',headers,body:'<svg onload=alert(1)></svg>'});assert.equal(response.status,415);const outside=path.join(dir,'outside.png');fs.writeFileSync(outside,png);fs.unlinkSync(site+'/asset.png');fs.symlinkSync(outside,site+'/asset.png');response=await fetch(editor.origin+'/__preview__/asset.png');assert.ok(response.status>=400);});
test('failed save rolls back all generated files',async t=>{const{site,dir}=fixture(),before=outputs(site);const loader=path.join(dir,'fail-write.mjs');fs.writeFileSync(loader,`import fs from 'node:fs';const original=fs.renameSync;let failed=false;fs.renameSync=function(from,to){if(!failed&&String(from).includes('/new/')&&String(to).endsWith('styles.css')){failed=true;throw new Error('Injected write failure');}return original.apply(this,arguments);};`);const editor=await start(t,site,loader),state=(await editor.api('state')).body;const r=await editor.api('save',{sourceHash:state.sourceHash,changes:[{path:'name',value:'Will not persist'}]});assert.ok(r.status>=400);assert.deepEqual(outputs(site),before);assert.equal((await editor.api('state')).body.canUndo,false);});
