import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
const root=new URL('..',import.meta.url).pathname;
const page=(title,body,head='')=>`<!doctype html><html lang="en"><head><title>${title}</title><meta name="description" content="${title} supplied description"><meta name="viewport" content="width=device-width,initial-scale=1">${head}</head><body><h1>${title}</h1>${body}</body></html>`;
function dir(){return fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'wd-launch-test-')))}
function audit(site){const result=spawnSync(process.execPath,[root+'scripts/launch-check.mjs',`--dir=${site}`,'--json'],{encoding:'utf8'});return{...result,report:JSON.parse(result.stdout)}}
test('whole-site audit detects missing destinations, fragments, assets and orphan pages',()=>{const site=dir();fs.mkdirSync(site+'/pages');fs.writeFileSync(site+'/index.html',page('Home','<a href="pages/contact.html?ref=home#contact">Contact</a><img src="picture.svg" alt="Original drawing">'));fs.writeFileSync(site+'/pages/contact.html',page('Contact','<p id="contact">Contact details.</p><a href="../index.html">Home</a>'));fs.writeFileSync(site+'/picture.svg','<svg xmlns="http://www.w3.org/2000/svg"/>');let r=audit(site);assert.equal(r.status,0,r.stdout+r.stderr);assert.notEqual(r.report.status,'fail');fs.writeFileSync(site+'/index.html',page('Home','<a href="pages/contact.html#absent">Contact</a><a href="missing.html">Missing page</a><img src="absent.png" alt="Missing drawing">'));fs.writeFileSync(site+'/orphan.html',page('Home','Unlinked page'));r=audit(site);assert.notEqual(r.status,0);const findings=JSON.stringify(r.report.findings);for(const token of ['absent','missing.html','orphan.html'])assert.ok(findings.includes(token),findings);});
test('local base href resolves navigation and SEO hard failures fail the aggregate',()=>{const site=dir();fs.mkdirSync(site+'/pages');fs.writeFileSync(site+'/index.html',page('Home','<a href="contact.html#contact">Contact</a>','<base href="/pages/">'));fs.writeFileSync(site+'/pages/contact.html',page('Contact','<p id="contact">Reach us</p><a href="/index.html">Home</a>'));let r=audit(site);assert.equal(r.status,0,r.stdout);fs.writeFileSync(site+'/index.html','<!doctype html><html lang="en"><body><p>No title or description</p></body></html>');r=audit(site);assert.notEqual(r.status,0);assert.equal(r.report.status,'fail');});
test('whole-site audit does not follow symlinks or inert template decoys',()=>{const site=dir(),outside=dir();fs.writeFileSync(site+'/index.html',page('Home','<template><a href="missing.html">Not rendered</a></template><script>const fake="<a href=missing.html>";</script>'));assert.equal(audit(site).status,0);fs.writeFileSync(outside+'/private.html',page('Private','Private sentinel'));fs.symlinkSync(outside+'/private.html',site+'/linked.html');const r=audit(site);assert.ok(r.status!==0||/symlink|symbolic.link/i.test(JSON.stringify(r.report)));assert.ok(!JSON.stringify(r.report).includes('Private sentinel'));});
function review(before,after){const site=dir();fs.writeFileSync(site+'/before.html',before);fs.writeFileSync(site+'/after.html',after);const r=spawnSync(process.execPath,[root+'scripts/copy-review.mjs',`--before=${site}/before.html`,`--after=${site}/after.html`,'--json'],{encoding:'utf8'});return{...r,report:JSON.parse(r.stdout)}}
test('copy change review includes button facts and qualifiers but excludes metadata',()=>{let r=review(page('Old metadata','<p>Repairs may take up to 20 days.</p><button>Pay $49</button>'),page('New metadata','<p>Repairs take 2 days.</p><button>Pay $499</button>'));assert.equal(r.report.status,'review_required');for(const token of ['$49','may','up to','20'])assert.ok(r.report.removedFactTokens.some(x=>x.value===token),JSON.stringify(r.report));assert.ok(r.report.changedBlocks.some(x=>x.before?.text==='Pay $49'));const unchanged=page('Same visible heading','<p>Same visible text</p>');r=review(unchanged,unchanged.replace('<title>Same visible heading</title>','<title>New metadata</title>'));assert.equal(r.status,0);assert.equal(r.report.status,'no_visible_change_detected');});
