import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const cli=fileURLToPath(new URL('../scripts/seo-check.mjs',import.meta.url));const good='<!doctype html><html lang="en"><head><title>Sample studio services</title><meta name="description" content="A clear description of the sample studio services."></head><body><main><h1>Sample studio</h1><p>Editable service details.</p><a href="#contact">Contact</a><section id="contact"><h2>Contact</h2><p>Contact details to be confirmed.</p></section></main></body></html>';
function run(html,args=[]){const file=join(mkdtempSync(join(tmpdir(),'wd-seo-')),'index.html');writeFileSync(file,html);const r=spawnSync(process.execPath,[cli,`--file=${file}`,'--json',...args],{encoding:'utf8',timeout:15000});assert.equal(readFileSync(file,'utf8'),html);return r}
test('local SEO check accepts basic truthful page and states live checks are not checked',()=>{const r=run(good);assert.equal(r.status,0,r.stderr+r.stdout);const result=JSON.parse(r.stdout);assert.match(JSON.stringify(result),/not_checked/);assert.match(JSON.stringify(result),/index|HTTP|robots/i)});
test('missing metadata and malformed structured data fail',()=>{for(const html of [good.replace(/<title>.*?<\/title>/,''),good.replace(/<meta name="description"[^>]+>/,''),good.replace('</head>','<script type="application/ld+json">{broken}</script></head>')]){const r=run(html);assert.notEqual(r.status,0);JSON.parse(r.stdout)}});
test('private indexing directives are warned and never removed',()=>{const r=run(good.replace('</head>','<meta name="robots" content="noindex,nosnippet"></head>'));JSON.parse(r.stdout);assert.match(r.stdout,/noindex/);assert.match(r.stdout,/warn/)});
test('script and comment headings cannot satisfy visible H1 convention',()=>{const r=run(good.replace('<h1>Sample studio</h1>','<!-- <h1>Fake</h1> --><script>const fake="<h1>Hidden</h1>";</script>'));assert.notEqual(r.status,0)});
test('explicit public URL mismatch is surfaced without fetching',()=>{const r=run(good.replace('</head>','<link rel="canonical" href="https://example.com/wrong"></head>'),['--url=https://example.com/right']);assert.match(r.stdout,/canonical/i);assert.match(r.stdout,/warn|fail/)});
test('invalid flags and missing input fail without mutation',()=>{const r=spawnSync(process.execPath,[cli,'--bogus'],{encoding:'utf8',timeout:15000});assert.notEqual(r.status,0)});

test('nosnippet alone is surfaced as an intentional AI/search preview restriction',()=>{const r=run(good.replace('</head>','<meta name="robots" content="nosnippet"></head>'));const report=JSON.parse(r.stdout);assert.ok(report.checks.some(c=>c.status==='warn'&&/nosnippet/i.test(c.evidence)));});

test('robots none is surfaced as restricted indexing',()=>{const r=run(good.replace('</head>','<meta name="robots" content="none"></head>'));const report=JSON.parse(r.stdout);assert.ok(report.checks.some(c=>c.id==='meta_robots'&&c.status==='warn'))});
test('inert template and textarea content cannot supply required page metadata',()=>{for(const tag of ['template','textarea']){const r=run('<!doctype html><html><body><'+tag+'>'+good+'</'+tag+'></body></html>');assert.notEqual(r.status,0)}});
test('HTML encoded canonical attributes compare against decoded public URL',()=>{const r=run(good.replace('</head>','<link rel="canonical" href="https://example.com/?a=1&amp;b=2"></head>'),['--url=https://example.com/?a=1&b=2']);const report=JSON.parse(r.stdout);assert.ok(report.checks.some(c=>c.id==='canonical'&&c.status==='pass'))});
